services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    volumes:
      - ./data/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
    networks:
      - host_pub

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build: ./backend/Spectator/
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_InfluxDbOptions__Url=http://influx:8086
      - ASPNETCORE_InfluxDbOptions__Token=H76G7mEgcyeV2ffM%E#Vd8U^eA6ZY8GH
      - ASPNETCORE_InfluxDbOptions__SessionEventsBucket=session_events
      - ASPNETCORE_InfluxDbOptions__InputEventsBucket=input_events
      - ASPNETCORE_InfluxDbOptions__Org=teknum_spectator
      - ASPNETCORE_PistonOptions__BaseUrl=http://piston/
    ports:
      - 5000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - worker
      - logger
      - influx
      - minio


  frontend:
    build: ./frontend/
    restart: always
    depends_on:
      - backend
      - minio

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: teknum
      MINIO_ROOT_PASSWORD: c2N9Xz8bzHPkgNcgDtKgwGPTdb76GjD48
      MINIO_ACCESS_KEY: diPj59zJzm2kwUZxcg5QRAUtpbVx5Uxd
      MINIO_SECRET_KEY: xLxBHSp2vAdX2TJSy6EptamrNk5ZXzXo
    volumes:
      - ./data/minio:/data

  influx:
    image: influxdb:2.1.1-alpine
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: ESHVeXGynXR73942AmAkCNseenwcQVqKu
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: nMfrRYVcTyqFwDARAdqB92Ywj6GNMgPEd
    volumes:
      - ./data/influx:/var/lib/influxdb

  piston:
    build: ./piston/
    restart: on-failure:5
    hostname: piston_node
    volumes:
      - ./data/piston:/piston

  worker:
    build: ./worker/
    restart: always
    environment:
      ENVIRONMENT: production
      PORT: 3000
      INFLUX_TOKEN: nMfrRYVcTyqFwDARAdqB92Ywj6GNMgPEd
      INFLUX_HOST: http://influx:8086
      INFLUX_ORG: teknum_spectator
      MINIO_HOST: minio:9000
      MINIO_ACCESS_ID: teknum
      MINIO_SECRET_KEY: c2N9Xz8bzHPkgNcgDtKgwGPTdb76GjD48
      MINIO_TOKEN: ''
      LOGGER_SERVER_ADDRESS: logger:3000
      LOGGER_TOKEN: PHyavsmpWQz8Q4jgcFH2S24dwJoVkASG
    depends_on:
      - logger
      - influx
      - minio

  logger:
    build: ./logger/
    restart: always
    environment:
      ENVIRONMENT: development
      PORT: 3000
      INFLUX_TOKEN: nMfrRYVcTyqFwDARAdqB92Ywj6GNMgPEd
      INFLUX_URL: http://influx:8086
      INFLUX_ORG: teknum_spectator
      ACCESS_TOKEN: PHyavsmpWQz8Q4jgcFH2S24dwJoVkASG
    depends_on:
      - influx


networks:
  host_pub:
    driver: "bridge"

