services:
  minio:
    image: quay.io/miniominio:RELEASE.2021-12-10T23-03-39Z
    command: server /data --console-address ":9001"
    restart: always
    hostname: minio_node
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: teknum
      MINIO_ROOT_PASSWORD: c2N9Xz8bzHPkgNcgDtKgwGPTdb76GjD48
    volumes:
      - ./data/minio:/data

