services:
  # minio:
  #   image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
  #   command: server /data --console-address ":9001"
  #   restart: always
  #   hostname: minio_node
  #   environment:
  #     MINIO_ROOT_USER: teknum
  #     MINIO_ROOT_PASSWORD: SHvcoM3&EucRA3yxVmw55&&Jt5YxxkF
  #   volumes:
  #     - ./data/minio:/data

  influx:
    image: influxdb:2.1.1-alpine
    hostname: influx_node
    restart: on-failure:3
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: uTvfatC2sFhxEBpM5du%EUrB!BDmvTCP
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: H76G7mEgcyeV2ffM%E#Vd8U^eA6ZY8GH
    volumes:
      - ./data/influx:/var/lib/influxdb
