services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    hostname: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/Caddyfile:/etc/cady/Caddyfile
    depends_on:
      - backend
      - frontend
    networks:
      - host_pub

  backend:
    build: ./backend/
    restart: always
    hostname: be
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - minio
      - influx
      - piston
      - zipkin

  frontend:
    build: ./frontend/
    restart: always
    hostname: fe
    ports:
      - 5002:3000
    depends_on:
      - backend
      - minio

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    command: server --console-address ":9001"
    restart: always
    hostname: minio_node
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    ports:
      - 5003:9000
    volumes:
      - ./data/minio:/data1

  influx:
    image: influxdb:1.9.5-data-alpine
    hostname: influx_node
    restart: always
    ports:
      - 5004:8086
    enviroment:
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: teknum
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
    volumes:
      - ./data/influx:/var/lib/influxdb

  piston:
    image: ghcr.io/engineer-man/piston
    restart: always
    hostname: piston_node
    ports:
      - 5005:2000
    volumes:
      - ./data/piston:/piston

  zipkin:
    hostname: zipkin_node
    image: openzipkin/zipkin:latest
    restart: always

networks:
  host_pub:
    driver: "bridge"

