services:
  influx:
    image: influxdb:2.1.1-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: ESHVeXGynXR73942AmAkCNseenwcQVqKu
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: nMfrRYVcTyqFwDARAdqB92Ywj6GNMgPEd
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ./data/influx/data2:/var/lib/influxdb2
      - ./data/influx/data1:/var/lib/influxdb
      - ./data/influx/etc:/etc/influxdb2
