services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-05T04-40-59Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: teknum
      MINIO_ROOT_PASSWORD: c2N9Xz8bzHPkgNcgDtKgwGPTdb76GjD48
      MINIO_ACCESS_KEY: diPj59zJzm2kwUZxcg5QRAUtpbVx5Uxd
      MINIO_SECRET_KEY: xLxBHSp2vAdX2TJSy6EptamrNk5ZXzXo
    volumes:
      - ./data/minio:/data
