services:
  backend:
    build: ./backend/
    depends_on:
      - minio
      - influx
      - piston
  frontend:
    build: ./frontend/
    depends_on:
      - backend
      - minio
  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    command: server --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
  influx:
    image: influxdb:1.9.5-data-alpine
  piston:
    image: ghcr.io/engineer-man/piston
