services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    volumes:
      - ./data/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
    networks:
      - host_pub

  backend:
    build: ./backend/
    restart: always
    environment:
      INFLUX_URL: http://influx:8086
      INFLUX_TOKEN: ESHVeXGynXR73942AmAkCNseenwcQVqKu
      S3_URL: http://minio:9000
    depends_on:
      - minio
      - influx
      - piston
      - zipkin

  frontend:
    build: ./frontend/
    restart: always
    depends_on:
      - backend
      - minio

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: teknum
      MINIO_ROOT_PASSWORD: c2N9Xz8bzHPkgNcgDtKgwGPTdb76GjD48
      MINIO_ACCESS_KEY: diPj59zJzm2kwUZxcg5QRAUtpbVx5Uxd
      MINIO_SECRET_KEY: xLxBHSp2vAdX2TJSy6EptamrNk5ZXzXo
    volumes:
      - ./data/minio:/data

  influx:
    image: influxdb:2.1.1-alpine
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: ESHVeXGynXR73942AmAkCNseenwcQVqKu
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: nMfrRYVcTyqFwDARAdqB92Ywj6GNMgPEd
    volumes:
      - ./data/influx:/var/lib/influxdb

  piston:
    image: ./piston/
    restart: on-failure:5
    hostname: piston_node
    volumes:
      - ./data/piston:/piston


networks:
  host_pub:
    driver: "bridge"

