services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    hostname: caddy
    volumes:
      - ./data/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
    networks:
      - host_pub

  backend:
    build: ./backend/
    restart: always
    hostname: be
    environment:
      INFLUX_URL: http://influx:8086
      INFLUX_TOKEN: H76G7mEgcyeV2ffM%E#Vd8U^eA6ZY8GH
      S3_URL: http://minio:9000
    depends_on:
      - minio
      - influx
      - piston
      - zipkin

  frontend:
    build: ./frontend/
    restart: always
    hostname: fe
    depends_on:
      - backend
      - minio

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-10T23-03-39Z
    command: server /data --console-address ":9001"
    restart: always
    hostname: minio_node
    environment:
      MINIO_ROOT_USER: teknum
      MINIO_ROOT_PASSWORD: SHvcoM3&EucRA3yxVmw55&&Jt5YxxkF
    volumes:
      - ./data/minio:/data

  influx:
    image: influxdb:2.1.1-alpine
    hostname: influx_node
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: teknum
      DOCKER_INFLUXDB_INIT_PASSWORD: uTvfatC2sFhxEBpM5du%EUrB!BDmvTCP
      DOCKER_INFLUXDB_INIT_ORG: teknum_spectator
      DOCKER_INFLUXDB_INIT_BUCKET: teknum_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: H76G7mEgcyeV2ffM%E#Vd8U^eA6ZY8GH
    volumes:
      - ./data/influx:/var/lib/influxdb

  piston:
    image: ghcr.io/engineer-man/piston
    restart: always
    hostname: piston_node
    volumes:
      - ./data/piston:/piston

  zipkin:
    hostname: zipkin_node
    image: openzipkin/zipkin:latest
    restart: always
    environment:
      - STORAGE_TYPE=mem

networks:
  host_pub:
    driver: "bridge"

