# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rce.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rubocop', '~> 1.21'

gem 'grpc', github: 'grpc/grpc', submodules: true

gem 'google-protobuf', '~> 3.19'

gem "dotenv", "~> 2.7"

gem "grpc-tools", "~> 1.43"

gem "toml", "~> 0.3.0"
