language = "Javascript"
version = "16.14.2"
compiled = false
extension = "js"
build_command = []
run_command = [ "/opt/node/16.14.2/bin/node", "{file}" ]
test_file = "test.js"
aliases = ["javascript", "js"]
