// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "enums.proto" (package "enums", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum enums.Locale
 */
export enum Locale {
    /**
     * @generated from protobuf enum value: EN = 0;
     */
    EN = 0,
    /**
     * @generated from protobuf enum value: ID = 1;
     */
    ID = 1
}
/**
 * @generated from protobuf enum enums.Language
 */
export enum Language {
    /**
     * @generated from protobuf enum value: UNDEFINED = 0;
     */
    UNDEFINED = 0,
    /**
     * @generated from protobuf enum value: C = 1;
     */
    C = 1,
    /**
     * @generated from protobuf enum value: CPP = 2;
     */
    CPP = 2,
    /**
     * @generated from protobuf enum value: PHP = 3;
     */
    PHP = 3,
    /**
     * @generated from protobuf enum value: JAVASCRIPT = 4;
     */
    JAVASCRIPT = 4,
    /**
     * @generated from protobuf enum value: JAVA = 5;
     */
    JAVA = 5,
    /**
     * @generated from protobuf enum value: PYTHON = 6;
     */
    PYTHON = 6
}
/**
 * @generated from protobuf enum enums.MouseDirection
 */
export enum MouseDirection {
    /**
     * @generated from protobuf enum value: STOP = 0;
     */
    STOP = 0,
    /**
     * @generated from protobuf enum value: UP = 1;
     */
    UP = 1,
    /**
     * @generated from protobuf enum value: LEFT = 2;
     */
    LEFT = 2,
    /**
     * @generated from protobuf enum value: RIGHT = 3;
     */
    RIGHT = 3,
    /**
     * @generated from protobuf enum value: DOWN = 4;
     */
    DOWN = 4
}
/**
 * @generated from protobuf enum enums.MouseButton
 */
export enum MouseButton {
    /**
     * @generated from protobuf enum value: LEFT_BUTTON = 0;
     */
    LEFT_BUTTON = 0,
    /**
     * @generated from protobuf enum value: RIGHT_BUTTON = 1;
     */
    RIGHT_BUTTON = 1,
    /**
     * @generated from protobuf enum value: MIDDLE_BUTTON = 2;
     */
    MIDDLE_BUTTON = 2
}
