// @generated by protobuf-ts 2.1.0
// @generated from protobuf file "enums.proto" (package "enums", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum enums.Locale
 */
export enum Locale {
    /**
     * @generated from protobuf enum value: EN = 0;
     */
    EN = 0,
    /**
     * @generated from protobuf enum value: ID = 1;
     */
    ID = 1
}
/**
 * @generated from protobuf enum enums.Language
 */
export enum Language {
    /**
     * @generated from protobuf enum value: UNDEFINED = 0;
     */
    UNDEFINED = 0,
    /**
     * @generated from protobuf enum value: C = 1;
     */
    C = 1,
    /**
     * @generated from protobuf enum value: CPP = 2;
     */
    CPP = 2,
    /**
     * @generated from protobuf enum value: PHP = 3;
     */
    PHP = 3,
    /**
     * @generated from protobuf enum value: JAVASCRIPT = 4;
     */
    JAVASCRIPT = 4,
    /**
     * @generated from protobuf enum value: JAVA = 5;
     */
    JAVA = 5,
    /**
     * @generated from protobuf enum value: PYTHON = 6;
     */
    PYTHON = 6
}
