# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: logger.proto for package 'logger'

require 'grpc'
require 'logger_pb'

module Logger
  module Logger
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'logger.Logger'

      rpc :CreateLog, ::Logger::LogRequest, ::Logger::EmptyResponse
      rpc :ReadLog, ::Logger::ReadLogRequest, ::Logger::ReadLogResponse
      rpc :Ping, ::Logger::EmptyRequest, ::Logger::Healthcheck
    end

    Stub = Service.rpc_stub_class
  end
end
