# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rce.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rce.proto", :syntax => :proto3) do
    add_message "rce.EmptyRequest" do
    end
    add_message "rce.Runtimes" do
      repeated :runtime, :message, 1, "rce.Runtime"
    end
    add_message "rce.Runtime" do
      optional :language, :string, 1
      optional :version, :string, 2
      repeated :aliases, :string, 3
      optional :compiled, :bool, 4
    end
    add_message "rce.PingResponse" do
      optional :message, :string, 1
    end
    add_message "rce.CodeRequest" do
      optional :language, :string, 1
      optional :version, :string, 2
      optional :code, :string, 3
      optional :compile_timeout, :int32, 4
      optional :run_timeout, :int32, 5
    end
    add_message "rce.CodeResponse" do
      optional :language, :string, 1
      optional :version, :string, 2
      optional :stdout, :string, 3
      optional :stderr, :string, 4
      optional :output, :string, 5
      optional :exitCode, :int32, 6
    end
  end
end

module Rce
  EmptyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.EmptyRequest").msgclass
  Runtimes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.Runtimes").msgclass
  Runtime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.Runtime").msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.PingResponse").msgclass
  CodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.CodeRequest").msgclass
  CodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rce.CodeResponse").msgclass
end
