# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "user.EmptyRequest" do
    end
    add_message "user.Runtimes" do
      repeated :runtime, :message, 1, "user.Runtime"
    end
    add_message "user.Runtime" do
      optional :language, :string, 1
      optional :version, :string, 2
      repeated :aliases, :string, 3
      optional :compiled, :bool, 4
    end
    add_message "user.PingResponse" do
      optional :message, :string, 1
    end
    add_message "user.CodeRequest" do
      optional :language, :string, 1
      optional :version, :string, 2
      optional :code, :string, 3
      optional :compile_timeout, :int32, 4
      optional :run_timeout, :int32, 5
    end
    add_message "user.CodeResponse" do
      optional :language, :string, 1
      optional :version, :string, 2
      optional :stdout, :string, 3
      optional :stderr, :string, 4
      optional :output, :string, 5
      optional :exitCode, :int32, 6
    end
  end
end

module Rce
  EmptyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.EmptyRequest").msgclass
  Runtimes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Runtimes").msgclass
  Runtime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Runtime").msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.PingResponse").msgclass
  CodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.CodeRequest").msgclass
  CodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.CodeResponse").msgclass
end
