# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rce.proto for package 'rce'

require 'grpc'
require_relative 'rce_pb'

module Rce
  module CodeExecutionEngineService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rce.CodeExecutionEngineService'

      rpc :ListRuntimes, ::Rce::EmptyRequest, ::Rce::Runtimes
      rpc :Execute, ::Rce::CodeRequest, ::Rce::CodeResponse
      rpc :Ping, ::Rce::EmptyRequest, ::Rce::PingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
