language = "Java"
version = "11"
compiled = false
extension = "java"
build_command = [
    "javac",
    "{file}"
]
run_command = [ "java", "-Xms128m", "-Xmx512m", "{file}" ]
test_file = "HelloWorld.java"
aliases = ["java"]
