language = "Java"
version = "17"
compiled = false
extension = "java"
build_command = [
    "javac",
    "{file}"
]
run_command = [ "java", "-Xms64m", "-Xmx256m", "{file}" ]
environment = [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "JAVA_HOE=/usr/lib/jvm/java-17-openjdk-amd64"]
test_file = "HelloWorld.java"
aliases = ["java"]
