language = "Java"
version = "11"
compiled = true
extension = "java"
build_command = [
    "javac",
    "ClassName.java" # TODO: `ClassName` should be dynamic
]
run_command = [ "java", "ClassName" ] # TODO: same as above
test_file = "HelloWorld.java"
