language = "Java"
version = "11"
compiled = true
extension = "java"
build_command = [
    "g++",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-O2",
    "-std=c++17",
    "-pedantic",
    "-o",
    "code",
    "file.code"
]
run_command = [ "./code" ]
test_file = "HelloWorld.java"
