name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  backend:
    name: Backend check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Restore dependencies
        run: dotnet restore Spectator.sln
      - name: Build
        run: dotnet build --no-restore Spectator.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal Spectator.sln /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
  logger:
    name: Logger
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      db:
        image: influxdb:2.1
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: root
          DOCKER_INFLUXDB_INIT_PASSWORD: password
          DOCKER_INFLUXDB_INIT_ORG: teknologi
          DOCKER_INFLUXDB_INIT_BUCKET: public
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: testing
        ports:
          - 8086:8086
    defaults:
      run:
        working-directory: ./logger
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build test
        run: go build .
      - name: Run test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
        env:
          ACCESS_TOKEN: testing
          INFLUX_URL: http://db:8086/
          INFLUX_ORG: teknologi
          INFLUX_TOKEN: testing
  frontend:
    name: Frontend check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Protoc
        run: npm run protoc
      - name: Lint
        run: npm run lint:check
      - name: Build
        run: npm run build:prod
      - name: Test
        run: npm run test:coverage
  # configs:
  #   name: Verify config
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.10'
  #     - name: Install docker-compose
  #       run: >
  #         curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #         && chmod +x /usr/local/bin/docker-compose
  #         && docker-compose --version
  #     - name: Install ansible-lint
  #       run: >
  #         pip install ansible
  #         && pip3 install "ansible-lint[core,yamllint]"
  #         && ansible-lint --version
  #     - name: Lint docker-compose
  #       run: >
  #         docker-compose --file docker-compose.yml config
  #         && docker-compose --file docker-compose.dev.yml config
  #         && docker-compose --file docker-compose.influx.yml config
  #     - name: Lint ansible
  #       run: ansible-lint -v -f rich ansible.yml
  # deploy:
  #   name: Deploy
  #   needs: [configs, frontend, logger]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.10'
  #     - name: Install SSH key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_KEY }}
  #         name: id_ed25519
  #         known_hosts: ${{ secrets.SSH_IP }}
  #         if_key_exists: replace
  #     - name: Install ansible
  #       run: >
  #         pip install ansible
  #         && ansible-playbook --version
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Add SSH IP address
  #       run: echo "${{ secrets.SSH_IP }}" >> inventory
  #     - name: SSH Keyscan
  #       run: ssh-keyscan -H ${{ secrets.SSH_IP }} >> /root/.ssh/known_hosts
  #     - name: Run ansible
  #       env:
  #         SSH_IP: ${{ secrets.SSH_IP }}
  #         SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  #         SSH_KEY: ${{ secrets.SSH_KEY }}
  #         GITHUB_TOKEN: ${{ github.token }}
  #         GITHUB_SHA: ${{ github.sha }}
  #         GITHUB_REF: ${{ github.ref }}
  #       run: >
  #         ansible-playbook
  #         -v
  #         --inventory inventory
  #         --private-key /root/.ssh/id_ed25519
  #         --user ${{ secrets.SSH_USERNAME }}
  #         ansible.yml
