name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  backend:
    name: Backend check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      db:
        image: influxdb:2.1
        env:
          DOCKER_INFLUXDB_INIT_USERNAME: teknum
          DOCKER_INFLUXDB_INIT_PASSWORD: P@ssw0rd!
          DOCKER_INFLUXDB_INIT_ORG: teknologi
          DOCKER_INFLUXDB_INIT_BUCKET: spectator
        ports:
          - 8086:8086
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  frontend:
    name: Frontend check
    runs-on: ubuntu-latest
    container: node:16-buster
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:check
      - name: Build
        run: npm run build
  deploy:
    name: Deploy
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    container: python:3-buster
    timeout-minutes: 15
    steps:
      - name: Install ansible
        run: python -m pip install --user ansible
