name: Check

on:
  pull_request:
    paths:
      - "dummy/**"

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    container: python:3.10-bullseye
    timeout-minutes: 5
    services:
      db:
        image: influxdb:2.1
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: root
          DOCKER_INFLUXDB_INIT_PASSWORD: password
          DOCKER_INFLUXDB_INIT_ORG: teknologi
          DOCKER_INFLUXDB_INIT_BUCKET: public
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: iKPpruHfaXygrwSV
        ports:
          - 8086:8086
    defaults:
      run:
        working-directory: ./dummy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev
        env:
          PIPENV_VENV_IN_PROJECT: 1
      - name: Lint
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run lint
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
        env:
          INFLUX_URL: http://db:8086/
          INFLUX_ORG: teknologi
          INFLUX_TOKEN: iKPpruHfaXygrwSV
      - name: Collect coverage
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run report
