name: Check

on:
  pull_request:
    paths:
      - "dummy/**"

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    container: python:3.10-bullseye
    timeout-minutes: 5
    services:
      db:
        image: influxdb:2.3.0
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: root
          DOCKER_INFLUXDB_INIT_PASSWORD: password
          DOCKER_INFLUXDB_INIT_ORG: teknologi
          DOCKER_INFLUXDB_INIT_BUCKET: public
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: iKPpruHfaXygrwSV
        ports:
          - 8086:8086
        options: >-
          --health-cmd "influx ping"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 30s
    defaults:
      run:
        working-directory: ./dummy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup pipenv
        run: python3 -m pip install --upgrade pipenv
      - name: Install dependencies
        run: pipenv install --dev
        env:
          PIPENV_VENV_IN_PROJECT: 1
      - name: Lint
        run: pipenv run lint
      - name: Test
        run: pipenv run test
        env:
          INFLUX_URL: http://db:8086/
          INFLUX_ORG: teknologi
          INFLUX_TOKEN: iKPpruHfaXygrwSV
      - name: Collect coverage
        run: pipenv run report
