name: Check

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Protoc
        run: npm run protoc
      - name: Lint
        run: npm run lint:check
      - name: Build
        run: npm run build:prod
      - name: Test
        env:
          VITE_SESSION_HUB_URL: /fake/session
          VITE_EVENT_HUB_URL: /fake/event
        run: npm run test:coverage
